### ISSUE TITLE
The error that appears when running the code.

### ISSUE THREAD

**Issue by nuistji** [asrafulashiq/dynamic-cdfsl#2]
Excellent work and thanks for your sharing！ When I run your code, the following error appears: 

OmegaConf.register_resolver(name, f)
In 'config': Could not find 'data/default_data'

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/jifanfan/dynamic-cdfsl2/configs
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I have changed the dirctories of the data, and I used the environments that the requirement.txt provides.  I ran your code on Ubuntu 18.04.06 and used RTX3090 GPU. Thank you very much!

**Comment by asrafulashiq** [comment]
One file was missing. You may want to try again.

**Comment by nuistji** [comment]
> One file was missing. You may want to try again.

Thank you for your reply and it work!

**Comment by nuistji** [comment]
Hi! I have met another problem, when I ran on ISIC and ChestX data, it appears the following error:
Traceback (most recent call last):
  File "main.py", line 65, in hydra_main
    main(cfg, lt_system)
  File "main.py", line 56, in main
    return trainer.fit(model)
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 509, in fit
    results = self.accelerator_backend.train()
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 57, in train
    return self.train_or_test()
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in train
    self.train_loop.reset_train_val_dataloaders(model)
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 242, in reset_train_val_dataloaders
    self.trainer.reset_train_dataloader(model)
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 139, in reset_train_dataloader
    self.train_dataloader = self.request_dataloader(model.train_dataloader)
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 310, in request_dataloader
    dataloader = dataloader_fx()
  File "/home/jifanfan/dynamic-cdfsl/system/multiloader_mixin.py", line 11, in train_dataloader
    self.build_unlabel_loader()
  File "/home/jifanfan/dynamic-cdfsl/system/multiloader_mixin.py", line 34, in build_unlabel_loader
    unlabel_kwrgs={"filter_data": False})
  File "/home/jifanfan/dynamic-cdfsl/data_loader/data_module.py", line 146, in get_unlabel_dataloader
    **unlabel_kwrgs)
  File "/home/jifanfan/dynamic-cdfsl/data_loader/utils_data.py", line 521, in get_unlabel_loader
    **data_loader_params)
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I noticed that there is a directory named 'images_resized' in Class ISIC and ChestX in additional_data.py. How can I get the images in this directory? Thanks!
