### ISSUE TITLE
Error occurs when running on ISIC/ChestX datasets.

### ISSUE THREAD

**Issue by nuistji** [asrafulashiq/dynamic-cdfsl#3]

**Comment by nuistji** [comment]
Hi, I met another problem when I ran on ISIC/ChestX:Traceback (most recent call last):
  File "main.py", line 65, in hydra_main
    main(cfg, lt_system)
  File "main.py", line 56, in main
    return trainer.fit(model)
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 509, in fit
    results = self.accelerator_backend.train()
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 57, in train
    return self.train_or_test()
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in train
    self.train_loop.reset_train_val_dataloaders(model)
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 242, in reset_train_val_dataloaders
    self.trainer.reset_train_dataloader(model)
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 139, in reset_train_dataloader
    self.train_dataloader = self.request_dataloader(model.train_dataloader)
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 310, in request_dataloader
    dataloader = dataloader_fx()
  File "/home/jifanfan/dynamic-cdfsl/system/multiloader_mixin.py", line 11, in train_dataloader
    self.build_unlabel_loader()
  File "/home/jifanfan/dynamic-cdfsl/system/multiloader_mixin.py", line 34, in build_unlabel_loader
    unlabel_kwrgs={"filter_data": False})
  File "/home/jifanfan/dynamic-cdfsl/data_loader/data_module.py", line 146, in get_unlabel_dataloader
    **unlabel_kwrgs)
  File "/home/jifanfan/dynamic-cdfsl/data_loader/utils_data.py", line 523, in get_unlabel_loader
    **data_loader_params)
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by senamW** [comment]
Hi, i got the same problem when running on ISIC/ChestX datasets. Have you solved the problem? I would appreciate it if you can give me some suggestions.

**Comment by senamW** [comment]
Hi, I got the same error when running on ISIC/ChestX datasets.Have you solved the problem? I would appreciate it if you can give me some suggestions.

> Hi, I met another problem when I ran on ISIC/ChestX:Traceback (most recent call last): File "main.py", line 65, in hydra_main main(cfg, lt_system) File "main.py", line 56, in main return trainer.fit(model) File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 509, in fit results = self.accelerator_backend.train() File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 57, in train return self.train_or_test() File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test results = self.trainer.train() File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in train self.train_loop.reset_train_val_dataloaders(model) File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 242, in reset_train_val_dataloaders self.trainer.reset_train_dataloader(model) File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 139, in reset_train_dataloader self.train_dataloader = self.request_dataloader(model.train_dataloader) File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 310, in request_dataloader dataloader = dataloader_fx() File "/home/jifanfan/dynamic-cdfsl/system/multiloader_mixin.py", line 11, in train_dataloader self.build_unlabel_loader() File "/home/jifanfan/dynamic-cdfsl/system/multiloader_mixin.py", line 34, in build_unlabel_loader unlabel_kwrgs={"filter_data": False}) File "/home/jifanfan/dynamic-cdfsl/data_loader/data_module.py", line 146, in get_unlabel_dataloader **unlabel_kwrgs) File "/home/jifanfan/dynamic-cdfsl/data_loader/utils_data.py", line 523, in get_unlabel_loader **data_loader_params) File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 262, in **init** sampler = RandomSampler(dataset, generator=generator) # type: ignore File "/home/jifanfan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 104, in **init** "value, but got num_samples={}".format(self.num_samples)) ValueError: num_samples should be a positive integer value, but got num_samples=0
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
