### ISSUE TITLE
Error occurs when running on ISIC/ChestX datasets

### ISSUE THREAD

**Issue by senamW** [asrafulashiq/dynamic-cdfsl#6]
Hi, I got an error when running on ISIC/ChestX datasets. I would appreciate it if you can give me some suggestions.
Traceback (most recent call last):
  File "main.py", line 65, in hydra_main
    main(cfg, lt_system)
  File "main.py", line 56, in main
    return trainer.fit(model)
  File "/home/wlc/anaconda3/envs/Dy/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 509, in fit
    results = self.accelerator_backend.train()
  File "/home/wlc/anaconda3/envs/Dy/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 57, in train
    return self.train_or_test()
  File "/home/wlc/anaconda3/envs/Dy/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/wlc/anaconda3/envs/Dy/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in train
    self.train_loop.reset_train_val_dataloaders(model)
  File "/home/wlc/anaconda3/envs/Dy/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 242, in reset_train_val_dataloaders
    self.trainer.reset_train_dataloader(model)
  File "/home/wlc/anaconda3/envs/Dy/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 139, in reset_train_dataloader
    self.train_dataloader = self.request_dataloader(model.train_dataloader)
  File "/home/wlc/anaconda3/envs/Dy/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 310, in request_dataloader
    dataloader = dataloader_fx()
  File "/home/wlc/dynamic-cdfsl-master/system/multiloader_mixin.py", line 11, in train_dataloader
    self.build_unlabel_loader()
  File "/home/wlc/dynamic-cdfsl-master/system/multiloader_mixin.py", line 27, in build_unlabel_loader
    _dloader = self.dm.get_unlabel_dataloader(
  File "/home/wlc/dynamic-cdfsl-master/data_loader/data_module.py", line 137, in get_unlabel_dataloader
    base_loader, unlabel_dataset = datamgr.get_unlabel_loader(
  File "/home/wlc/dynamic-cdfsl-master/data_loader/utils_data.py", line 521, in get_unlabel_loader
    data_loader = torch.utils.data.DataLoader(dataset,
  File "/home/wlc/anaconda3/envs/Dy/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/home/wlc/anaconda3/envs/Dy/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 103, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by asrafulashiq** [comment]
Hi,

It seems that there is no sample in the dataset, may be some path issues. Please check your ISIC/ChestX dataset directory, and make sure the path matches with the path mentioned in the code: data_loader/additional_data.py. 

For ISIC, check this line: https://github.com/asrafulashiq/dynamic-cdfsl/blob/1af001370bd996bb55aba28381cce8b66de31379/data_loader/additional_data.py#L190

For ChestX: https://github.com/asrafulashiq/dynamic-cdfsl/blob/1af001370bd996bb55aba28381cce8b66de31379/data_loader/additional_data.py#L119

**Comment by senamW** [comment]
Much appreciated! I still haven't solved the problem though I changed it.

> Hi,
> 
> It seems that there is no sample in the dataset, may be some path issues. Please check your ISIC/ChestX dataset directory, and make sure the path matches with the path mentioned in the code: data_loader/additional_data.py.
> 
> For ISIC, check this line:
> 
> https://github.com/asrafulashiq/dynamic-cdfsl/blob/1af001370bd996bb55aba28381cce8b66de31379/data_loader/additional_data.py#L190
> 
> For ChestX:
> 
> https://github.com/asrafulashiq/dynamic-cdfsl/blob/1af001370bd996bb55aba28381cce8b66de31379/data_loader/additional_data.py#L119

**Comment by nuistji** [comment]
Hi，I have met the problem before. I just made the following changes: 
(Line 120)  image_path = ChestX_path+"/images_resized/"):--->image_path = ChestX_path + "/images/"):
(Line 191) image_path =  ISIC_path + "/ISIC2018_Input_Resized/"):--->image_path =  ISIC_path + "/ISIC2018_Task3_Training_Input/"):

Hope this can help you!

**Comment by nuistji** [comment]
@senamW Hi，I have met the problem before. I just made the following changes:
(Line 120) image_path = ChestX_path+"/images_resized/"):--->image_path = ChestX_path + "/images/"):
(Line 191) image_path = ISIC_path + "/ISIC2018_Input_Resized/"):--->image_path = ISIC_path + "/ISIC2018_Task3_Training_Input/"):

Hope this can help you!

**Comment by senamW** [comment]
@nuistji Much thanks！I have changed the path like you similarly, but I still got the same error. I run on EuroSAT/CropDiseases datasets successfully, so I really don't know the reasons.
